tp/documenter/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^company/$', CompanyView.as_view(), name='company-view'),
    url(r'^company/(?P<id>\d+)/$', CompanyDetailView.as_view(), name='company-detail-view'),
    url(r'^dealing/(?P<id>[a-z0-9-]{36})/$', DealingView.as_view(), name='dealing-view'),
]

tp/tp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('documenter.urls', namespace='doc'))
]

tp/documenter/models.py
import uuid
import datetime

from django.db import models

from .settings.countries import ISO31661a2

# Create your models here.

class CompanyCategory(models.Model):
    name = models.CharField(max_length=120)
    template_json = models.TextField()

    def __str__(self):
        return self.name


class Company(models.Model):
    shortname = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=255)
    category = models.ForeignKey(CompanyCategory)
    country = models.CharField(max_length=2, choices=ISO31661a2)
    data_json = models.TextField(default='{}')
    begin = models.DateField(default=datetime.date.today())
    end = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name


class DealingCategory(models.Model):
    name = models.CharField(max_length=120)
    template_json = models.TextField(default='{}')

    def __str__(self):
        return self.name


class Dealing(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    category = models.ForeignKey(DealingCategory)
    title = models.CharField(max_length=255)
    begin = models.DateField(blank=True, null=True)
    end = models.DateField(blank=True, null=True)
    beneficiary = models.ManyToManyField(Company, related_name='dealing_as_beneficiary')
    supplier = models.ManyToManyField(Company, related_name='dealing_as_supplier')
    template_json = models.TextField(default='{}')
    data_json = models.TextField(default='{}')
    createdAt = models.DateTimeField(auto_now_add=True)
    lastModified = models.DateTimeField(auto_now=True)
    closed = models.BooleanField(default=False)
    external_visible = models.BooleanField(default=False)

    def __str__(self):
        return self.title

tp/documenter/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.db.models import Q
from django.db.models import Count, Case, When

from .models import Company, Dealing, DealingCategory

# Create your views here.


class CompanyView(View):

    def get(self, request, *args, **kwargs):
        c = Company.objects.all()
        return render(request, 'documenter/companies.html', context={'companies': c})


class CompanyDetailView(View):

    def get(self, request, *args, **kwargs):
        company = Company.objects.get(pk=self.kwargs['id'])
        categories = DealingCategory.objects.annotate(
            num_dealings=Count(Case(
                When(Q(dealing__beneficiary=company) | Q(dealing__supplier=company), then=1),
            ))
        )
        # categories = DealingCategory.objects.annotate(num_dealings=Count('dealing'))
        dealing_list = Dealing.objects.filter(Q(beneficiary=company) | Q(supplier=company))






        return render(request, 'documenter/company_detail.html', context={
            'company': company,
            'categories': categories,
            'dealing_list': dealing_list
        })


class DealingView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse('Hello World {0}'.format(kwargs['id']))

tp/documenter/templates/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/documenter.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

tp/documenter/templates/documenter/companies.html
{% extends 'base.html' %}

{% block title %}Gesellschaften{% endblock %}

{% block content %}

<div class="col-md-12">
    <h1>Übersicht über alle Gesellschaften</h1>
    <ul>
        {% for c in companies %}
            <li><a href="{% url 'doc:company-detail-view' id=c.id %}">{{ c.name }}</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

tp/documenter/templates/documenter/company_detail.html
{% extends 'base.html' %}
{% load static %}
{% load documenter_filter %}

{% block title %}{{ company.shortname }}{% endblock %}

{% block content %}

<div class="col-md-12">
    <h1>{{ company.name }} ({{ company.shortname }})</h1>
    <table>
        <tr>
            <td>Land</td>
            <td>{{ company.get_country_display }}</td>
        </tr>
        <tr>
            <td>Gesellschaftstyp</td>
            <td>{{ company.category }}</td>
        </tr>
        <tr>
            <td>Gültigkeit</td>
            <td>{{ company.begin|date_or_infinite }} - {{ company.end|date_or_infinite }}</td>
        </tr>
    </table>
    <div id="company_description">
        <h2>Gesellschaftsinformationen</h2>
        <div id="data-view">
            <App :initial-json-form='{{ company.data_json|safe }}'></App>
        </div>
    </div>
    <div id="dealing_list">
        <h2>Kategorien</h2>
        <ul>
            {% for category in categories %}
                <li>{{ category.name }} ({{ category.num_dealings }})</li>
            {% endfor %}
        </ul>
    </div>
</div>

<script src="{% static 'js/vparser/dist/static/js/manifest.0f2b4add5cb959583e73.js' %}"></script>
<script src="{% static 'js/vparser/dist/static/js/vendor.fb7278e67ec8968a2895.js' %}"></script>
<script src="{% static 'js/vparser/dist/static/js/app.ec97e387c3d45fd49cd8.js' %}"></script>


{% endblock %}